// Generated by TInCuP Bijective Transformer
// This file contains CPO declarations transformed from `custom` functions
//
// To regenerate from custom declarations:
//   cpo-bidirectional from-custom input.hpp --output this_file.hpp

#pragma once

#include <tincup/tincup.hpp>

// CPO Declarations
// ===============================================================================

// TINCUP_GENERATED_FROM_CUSTOM
// TINCUP_ORIGINAL_SIGNATURE: template<typename T>
custom void serialize(const T& obj, std::ostream& os);
// TINCUP_FUNCTION_NAME: serialize
// TINCUP_TEMPLATE_PARAMS: typename T

inline constexpr struct serialize_ftor final : tincup::cpo_base<serialize_ftor> {
  TINCUP_CPO_TAG("serialize")
  inline static constexpr bool is_variadic = false;
  using tincup::cpo_base<serialize_ftor>::operator();

  template<typename OBJ, typename OS>
  constexpr auto operator()(OBJ&& obj, OS&& os) const
    noexcept(tincup::nothrow_invocable_c<serialize_ftor, OBJ, OS>)
    -> tincup::invocable_t<serialize_ftor, OBJ, OS> {
    return tincup::tag_invoke_cpo(*this, obj, os);
  }
} serialize;

template<typename T>
void tag_invoke(serialize_ftor, const T& obj, std::ostream& os) {
  // TODO: Implement
}

// TINCUP_GENERATED_FROM_CUSTOM
// TINCUP_ORIGINAL_SIGNATURE: template<typename T>
custom T clone(const T& x);
// TINCUP_FUNCTION_NAME: clone
// TINCUP_TEMPLATE_PARAMS: typename T

inline constexpr struct clone_ftor final : tincup::cpo_base<clone_ftor> {
  TINCUP_CPO_TAG("clone")
  inline static constexpr bool is_variadic = false;
  using tincup::cpo_base<clone_ftor>::operator();

  template<typename X>
  constexpr auto operator()(X&& x) const
    noexcept(tincup::nothrow_invocable_c<clone_ftor, X>)
    -> tincup::invocable_t<clone_ftor, X> {
    return tincup::tag_invoke_cpo(*this, x);
  }
} clone;

template<typename T>
T tag_invoke(clone_ftor, const T& x) {
  // TODO: Implement
  return {};  // Replace with actual implementation
}
